name: update
on:
  schedule:
    - cron: "5 3 * * 0"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: https://registry.npmjs.org
      - run: make deps
      - run: node update.js
      - run: |
          if [[ $(git status --porcelain --untracked-files=no) ]]; then
            git fetch --unshallow --quiet --tags
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -am "automated data update"
            make patch
          else
            echo "Nothing to commit"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
